
// Lista exhaustiva de países para usar en formularios
export const countries = [
    { value: 'Afghanistan', label: 'Afganistán' },
    { value: 'Albania', label: 'Albania' },
    { value: 'Germany', label: 'Alemania' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Saudi Arabia', label: 'Arabia Saudita' },
    { value: 'Algeria', label: 'Argelia' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Azerbaijan', label: 'Azerbaiyán' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bangladesh', label: 'Bangladés' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Bahrain', label: 'Baréin' },
    { value: 'Belgium', label: 'Bélgica' },
    { value: 'Belize', label: 'Belice' },
    { value: 'Benin', label: 'Benín' },
    { value: 'Belarus', label: 'Bielorrusia' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia and Herzegovina', label: 'Bosnia y Herzegovina' },
    { value: 'Botswana', label: 'Botsuana' },
    { value: 'Brazil', label: 'Brasil' },
    { value: 'Brunei', label: 'Brunéi' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Bhutan', label: 'Bután' },
    { value: 'Cape Verde', label: 'Cabo Verde' },
    { value: 'Cambodia', label: 'Camboya' },
    { value: 'Cameroon', label: 'Camerún' },
    { value: 'Canada', label: 'Canadá' },
    { value: 'Qatar', label: 'Catar' },
    { value: 'Chad', label: 'Chad' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: 'China' },
    { value: 'Cyprus', label: 'Chipre' },
    { value: 'Vatican City', label: 'Ciudad del Vaticano' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Comoros', label: 'Comoras' },
    { value: 'North Korea', label: 'Corea del Norte' },
    { value: 'South Korea', label: 'Corea del Sur' },
    { value: 'Ivory Coast', label: 'Costa de Marfil' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Croacia' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Denmark', label: 'Dinamarca' },
    { value: 'Dominica', label: 'Dominica' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Egypt', label: 'Egipto' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'United Arab Emirates', label: 'Emiratos Árabes Unidos' },
    { value: 'Eritrea', label: 'Eritrea' },
    { value: 'Slovakia', label: 'Eslovaquia' },
    { value: 'Slovenia', label: 'Eslovenia' },
    { value: 'Spain', label: 'España' },
    { value: 'United States', label: 'Estados Unidos' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Ethiopia', label: 'Etiopía' },
    { value: 'Philippines', label: 'Filipinas' },
    { value: 'Finland', label: 'Finlandia' },
    { value: 'Fiji', label: 'Fiyi' },
    { value: 'France', label: 'Francia' },
    { value: 'Gabon', label: 'Gabón' },
    { value: 'Gambia', label: 'Gambia' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Grenada', label: 'Granada' },
    { value: 'Greece', label: 'Grecia' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guinea', label: 'Guinea' },
    { value: 'Equatorial Guinea', label: 'Guinea Ecuatorial' },
    { value: 'Guinea-Bissau', label: 'Guinea-Bisáu' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Haiti', label: 'Haití' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Hungary', label: 'Hungría' },
    { value: 'India', label: 'India' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Iraq', label: 'Irak' },
    { value: 'Iran', label: 'Irán' },
    { value: 'Ireland', label: 'Irlanda' },
    { value: 'Iceland', label: 'Islandia' },
    { value: 'Marshall Islands', label: 'Islas Marshall' },
    { value: 'Solomon Islands', label: 'Islas Salomón' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Italy', label: 'Italia' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japan', label: 'Japón' },
    { value: 'Jordan', label: 'Jordania' },
    { value: 'Kazakhstan', label: 'Kazajistán' },
    { value: 'Kenya', label: 'Kenia' },
    { value: 'Kyrgyzstan', label: 'Kirguistán' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Lesotho', label: 'Lesoto' },
    { value: 'Latvia', label: 'Letonia' },
    { value: 'Lebanon', label: 'Líbano' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libya', label: 'Libia' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lithuania', label: 'Lituania' },
    { value: 'Luxembourg', label: 'Luxemburgo' },
    { value: 'North Macedonia', label: 'Macedonia del Norte' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Malaysia', label: 'Malasia' },
    { value: 'Malawi', label: 'Malaui' },
    { value: 'Maldives', label: 'Maldivas' },
    { value: 'Mali', label: 'Malí' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Morocco', label: 'Marruecos' },
    { value: 'Mauritius', label: 'Mauricio' },
    { value: 'Mauritania', label: 'Mauritania' },
    { value: 'Mexico', label: 'México' },
    { value: 'Micronesia', label: 'Micronesia' },
    { value: 'Moldova', label: 'Moldavia' },
    { value: 'Monaco', label: 'Mónaco' },
    { value: 'Mongolia', label: 'Mongolia' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Myanmar', label: 'Myanmar' },
    { value: 'Namibia', label: 'Namibia' },
    { value: 'Nauru', label: 'Nauru' },
    { value: 'Nepal', label: 'Nepal' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niger', label: 'Níger' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'Norway', label: 'Noruega' },
    { value: 'New Zealand', label: 'Nueva Zelanda' },
    { value: 'Oman', label: 'Omán' },
    { value: 'Netherlands', label: 'Países Bajos' },
    { value: 'Pakistan', label: 'Pakistán' },
    { value: 'Palau', label: 'Palaos' },
    { value: 'Panama', label: 'Panamá' },
    { value: 'Papua New Guinea', label: 'Papúa Nueva Guinea' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Peru', label: 'Perú' },
    { value: 'Poland', label: 'Polonia' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'United Kingdom', label: 'Reino Unido' },
    { value: 'Central African Republic', label: 'República Centroafricana' },
    { value: 'Czech Republic', label: 'República Checa' },
    { value: 'Congo', label: 'República del Congo' },
    { value: 'DR Congo', label: 'República Democrática del Congo' },
    { value: 'Dominican Republic', label: 'República Dominicana' },
    { value: 'Rwanda', label: 'Ruanda' },
    { value: 'Romania', label: 'Rumania' },
    { value: 'Russia', label: 'Rusia' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'Saint Kitts and Nevis', label: 'San Cristóbal y Nieves' },
    { value: 'San Marino', label: 'San Marino' },
    { value: 'Saint Vincent and the Grenadines', label: 'San Vicente y las Granadinas' },
    { value: 'Saint Lucia', label: 'Santa Lucía' },
    { value: 'Sao Tome and Principe', label: 'Santo Tomé y Príncipe' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Serbia', label: 'Serbia' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Sierra Leone', label: 'Sierra Leona' },
    { value: 'Singapore', label: 'Singapur' },
    { value: 'Syria', label: 'Siria' },
    { value: 'Somalia', label: 'Somalia' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Eswatini', label: 'Suazilandia' },
    { value: 'South Africa', label: 'Sudáfrica' },
    { value: 'Sudan', label: 'Sudán' },
    { value: 'South Sudan', label: 'Sudán del Sur' },
    { value: 'Sweden', label: 'Suecia' },
    { value: 'Switzerland', label: 'Suiza' },
    { value: 'Suriname', label: 'Surinam' },
    { value: 'Thailand', label: 'Tailandia' },
    { value: 'Tanzania', label: 'Tanzania' },
    { value: 'Tajikistan', label: 'Tayikistán' },
    { value: 'East Timor', label: 'Timor Oriental' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinidad and Tobago', label: 'Trinidad y Tobago' },
    { value: 'Tunisia', label: 'Túnez' },
    { value: 'Turkmenistan', label: 'Turkmenistán' },
    { value: 'Turkey', label: 'Turquía' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Ukraine', label: 'Ucrania' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Uzbekistan', label: 'Uzbekistán' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Yemen', label: 'Yemen' },
    { value: 'Djibouti', label: 'Yibuti' },
    { value: 'Zambia', label: 'Zambia' },
    { value: 'Zimbabwe', label: 'Zimbabue' },
];
